[project]
name = "mcp_demo"
version = "0.1.0"
description = "A simple demonstration MCP server"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastmcp>=2.11.2",
    "mcp>=1.10.0",
]

[project.optional-dependencies]
dev = ["debugpy>=1.8.8"]
